version: '3.2'
services:
  web1:
      build: ./php-on-apache
      container_name: web1
      tty: true
      expose:
          - '80'
      ports:
          - '8081:80'
      restart: always
  web2:
      build: ./php-on-apache
      container_name: web2
      tty: true
      expose:
          - '80'
      ports:
          - '8082:80'
      restart: always
  web3:
      build: ./php-on-apache
      container_name: web3
      tty: true
      expose:
          - '80'
      ports:
          - '8083:80'
      restart: always
  lb:
      build: ./lb-on-nginx
      container_name: lb
      depends_on:
          - web1
          - web2
          - web3
      tty: true
      links:
          - web1
          - web2
          - web3
      ports:
          - '8085:80'
      restart: always
      command: [nginx-debug, '-g', 'daemon off;']
